// Generated By AI

export interface LocationDepthLimits {
  min: number;
  max: number;
}

export interface Statistics {
  activeCount: number;
}

// يمكنك إضافة المزيد من الـ Roles المتوقعة هنا
export type CategoryRole =
  | "include_purpose_in_title"
  | "include_purpose_in_description"
  | "show_phone_number"
  | "allows_video"
  | "allows_delivery"
  | "dpv_mosaic_images"
  | "allow_ad_without_photo"
  | "disable_image_upload"
  | "non_editable_location"
  | "allow_jobs_quick_apply";

export type CategoryPurpose = "for-sale" | "for-rent";

export interface Category {
  id: number;
  name: string;
  name_l1: string;
  externalID: string;
  slug: string;
  level: number;
  parentID: number | null;
  displayPriority: number;
  purpose: CategoryPurpose;
  roles: CategoryRole[] | string[];
  locationDepthLimits: LocationDepthLimits;
  configurations: Record<string, any>; // لأنها حالياً كائنات فارغة
  statistics: Statistics;

  // حقول اختيارية تظهر في بعض الكائنات فقط
  nameShort?: string;
  nameShort_l1?: string;

  // حقول تظهر بـ null حالياً لكنها قد تحتوي على بيانات لاحقاً
  paaSections: any | null;
  templateConfigs: any | null;
  templateHashes: any | null;

  // خاصية تكرارية (Recursive) للأبناء
  children: Category[];

  parentSlug?: string;
}

// النوع الأساسي للمصفوفة اللي بعتها
export type CategoryList = Category[];

// --------------------------------------------------------

export interface CategoryFieldChoice {
  value: string;
  label: string;
  id: number;
  seoSlug: {
    ar: string;
    en: string;
  };
}

export interface CategoryField {
  id: number;
  name: string;
  attribute: string;
  valueType: "float" | "enum" | "string";
  filterType: "single_choice" | "multiple_choice" | "range";
  isMandatory: boolean;
  choices?: Array<CategoryFieldChoice>;
}

export interface FieldsResponse {
  [key: string]: {
    flatFields: CategoryField[];
    childrenFields: any;
    parentFieldLookup: { [key: string]: string };
  };
}
