
export const getIconPath = (name: string) =>{
    return `/assets/icons/${name}`;
}
export const getImagePath = (name: string) =>{
    return `/assets/images/${name}`;
}


// Generated By AI
export const groupAdsByCategory = (ads: any[], locale?: string) => {
    return ads.reduce((groups, ad) => {
    let sectionName = "Other";
    if (ad.ad_category_external_id === "126" || ad.ad_category_external_id === "95") sectionName = locale == "ar"? "شقق وفيلات":"Apartments & Villas";
    if (ad.ad_category_external_id === "9") sectionName = locale == "ar"? "الهواتف المحمولة":"Mobile Phones";
    if (ad.ad_category_external_id === "175") sectionName = locale == "ar"? "أجهزة الكمبيوتر المحمولة والمكتبية":"Laptops & Computers";
    if (ad.ad_category_external_id === "162") sectionName = locale == "ar"? "تكييف الهواء والتبريد والتدفئة":"AC, Cooling & Heating";
    if (ad.ad_category_external_id === "22") sectionName = locale == "ar"? "الدراجات النارية":"Motorcycles";

    if (!groups[sectionName]) {
      groups[sectionName] = [];
    }
    groups[sectionName].push(ad);
    return groups;
  }, {});
}